security:
  sso-login:
    csrf-excluded-url-patterns: /camunda/api/**
    keycloak-config:
      keycloakIssuerUrl: http://localhost:8083/realms/eabpmn
      keycloakAdminUrl: http://localhost:8083/admin/realms/eabpmn
      clientId: ${KEYCLOAK_CLIENT_ID}
      clientSecret: ${KEYCLOAK_CLIENT_SECRET}
      useUsernameAsCamundaUserId: false
      useGroupPathAsCamundaGroupId: true
      administratorGroupName: admin-group

# Spring Boot Security OAuth2 SSO
spring.security.oauth2:
  client:
    registration:
      keycloak:
        provider: keycloak
        client-id: ${KEYCLOAK_CLIENT_ID}
        client-secret: ${KEYCLOAK_CLIENT_SECRET}
        authorization-grant-type: authorization_code
        redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
        scope: openid, email
    provider:
      keycloak:
        issuer-uri: http://localhost:8083/realms/eabpmn
        authorization-uri: http://localhost:8083/realms/eabpmn/protocol/openid-connect/auth
        user-info-uri: http://localhost:8083/realms/eabpmn/protocol/openid-connect/userinfo
        token-uri: http://localhost:8083/realms/eabpmn/protocol/openid-connect/token
        jwk-set-uri: http://localhost:8083/realms/eabpmn/protocol/openid-connect/certs
        logout-uri: http://localhost:8083/realms/eabpmn/protocol/openid-connect/logout
        user-name-attribute: preferred_username